"----------
"	PREAMBLE
"----------
set nocompatible " be iMproved
filetype off " required!

"----------
" VUNDLE
"----------
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'vale1410/vim-minizinc'
Plugin 'scrooloose/syntastic'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'

call vundle#end()

syntax on
filetype plugin indent on " required!

"----------
" VIM SETTINGS
"----------
set magic                   " Enable extended regexes
set hlsearch                " highlight searches
set incsearch               " show the `best match so far' astyped
set ignorecase smartcase    " make searches case-insensitive, unless they
                            "   contain upper-case letters

set t_Co=256                " 256 colors terminal
set number                  " Enable line numbers
set showmatch               " show matching parenthesis
set title                   " Show the filename in the window title bar

set autoindent smartindent      " auto/smart indent
"set copyindent                  " copy previous indentation on auto indent
set softtabstop=2               " Tab key results in # spaces
set tabstop=2                   " Tab is # spaces
set shiftwidth=2                " The # of spaces for indenting.

set path+=**										" recursive file searches
set wildmenu										" tab completion

set makeprg=gcc									" compile C code

command! MakeTags !ctags -R .

set omnifunc=syntaxcomplete#Complete " Syntax aware code completion

set complete+=kspell

"switch spellcheck languages
let g:myLang = 0
let g:myLangList = [ "nospell", "sv_se", "en_us", "de_de" ]
function! MySpellLang()
	"loop through languages
	let g:myLang = g:myLang + 1
	if g:myLang >= len(g:myLangList) | let g:myLang = 0 | endif
	if g:myLang == 0 | set nospell | endif
	if g:myLang == 1 | setlocal spell spelllang=de_de | endif
	if g:myLang == 2 | setlocal spell spelllang=en_us | endif
	echo "language:" g:myLangList[g:myLang]
endf

map <F7> :call MySpellLang()<CR>
imap <F7> <C-o>:call MySpellLang()<CR>

" broilerplate mappings
nnoremap ,hmtl :-1read $HOME/.vim/skel/skel.html3jwf>a
nnoremap ,java :-1read $HOME/,vim/skel/skel.java
nnoremap ,tex  :-1read $HOME/.vim/skel/skel.tex
nnoremap ,p    :-1read $HOME/.vim/skel/p.tex

"----------
" SYNTASTIC
"----------

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
